### ISSUE TITLE
Works with "mac" caption buttons

### ISSUE THREAD

**Issue by Neikon** [sirlan-ff00ff/arcticfox-theme#5]
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/f5fee8a0-d0d5-4ff6-97c5-a27ff8667824)
the purple border is because this screenshot is from a private windows in Manjaro KDE Linux

To get this buttons import this code
round_caption_buttons.css
```css
/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/round_caption_buttons.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */

/* Make window-control - aka caption buttons round following theme text color. */

/* Uncomment the following line to use colorful icons ala MacOS */
.titlebar-button{ --uc-caption-background: var(--uc-caption-color) }

.titlebar-button { opacity: 0.6; --uc-caption-color: rgb(252,185,15) }
.titlebar-min    { opacity: 0.5; --uc-caption-color: rgb(36, 209, 49) }
.titlebar-close  { opacity: 0.7; --uc-caption-color: rgb(250, 55, 55) }

.titlebar-button:hover { opacity: 1 }

.titlebar-button {
  background: transparent !important;
  padding-inline: 6px !important;
  transition: opacity 0.2s ease;
}
.titlebar-close {	padding-right: 5px !important; }

.titlebar-button > .toolbarbutton-icon {
	list-style-image: none;
	border-radius: 10px;
  background: var(--uc-caption-background,currentColor) !important;
}

/* OPTIONAL - move caption buttons in tabs toolbar a bit upwards */
/* #TabsToolbar > .titlebar-buttonbox-container{ margin-bottom: var(--toolbarbutton-inner-padding) !important; } */

```
in userchrome.css
```css
/*code*/

@import url('round_caption_buttons.css');

/*more code*/

#nav-bar {
  /* ** width of the window control buttons (min max close)
        that the toolbar should take into account
     // change to 0 if using server side decorations
  */
  --wbt-wdt: 4.75rem; /*<-------- ajustment to fit better the buttoms*/

/*More code*/
```
