### ISSUE TITLE
Do not resize site content

### ISSUE THREAD

**Issue by Naezr** [sirlan-ff00ff/arcticfox-theme#6]
What should be done to make the site content not resize when the sidebar opens. I want the sidebar to overlay on top of the site and not resize it. Most sites are not adapted to frequent window resizing and do it very jerky. I really like this theme, but this one flaw makes it very frustrating to use

**Comment by sirlan-ff00ff** [comment]
resolved in commit https://github.com/sirlan-ff00ff/arcticfox-theme/commit/4013c7dbb1c4c848a396448d3063308342a79036

you can just copy-paste the new lines on your file

**Comment by Naezr** [comment]
Thank you so much, that's just incredible

**Comment by Neikon** [comment]
There is an error with this. You cannot use the top-right corner of the web. 

I cannot use this zone 
![imagen](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/1765319/6cc552c2-db37-48cf-abf2-b81e7173ea0b)

**Comment by Naezr** [comment]
It's really true, and I didn't even notice.

I tried to solve it and I succeeded. But now the sidebar doesn't appear if you hover over the indentation on the left where the navbar is. And the animations have become a bit broken. 

```#main-window:not([titlepreface*=" "]):has(#sidebar-box:hover) #navigator-toolbox,
#main-window:not([titlepreface*=" "]):has(#navigator-toolbox:hover) #navigator-toolbox, 
#main-window:not([titlepreface*=" "]):has(#navigator-toolbox:focus-within) #navigator-toolbox, 
#main-window:not([titlepreface*=" "]):has(toolbarbutton[open="true"]) #navigator-toolbox, 
#main-window:not([titlepreface*=" "]) #navigator-toolbox 
{
  position: absolute;
  z-index: 1;
}

#main-window:not([titlepreface*=" "]) #navigator-toolbox 
{
  position: absolute;
  z-index: -1;
}
```

![изображение](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/95460152/8b0903fe-6778-41ef-b1a8-74ec9ca6ec91)

**Comment by sirlan-ff00ff** [comment]
can you try with this addition

```css
/* line 413 */ #main-window:not([titlepreface*="|| "]) #navigator-toolbox {
  position: absolute;
  overflow: clip;  /* <-- add this */
  z-index: 2;
}

#main-window:not([titlepreface*="|| "]):has(#sidebar-box:hover) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:hover) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:focus-within) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(toolbarbutton[open="true"]) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(#sidebar-box:hover) #sidebar-box,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:hover) #sidebar-box,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:focus-within) #sidebar-box,
#main-window:not([titlepreface*="|| "]):has(toolbarbutton[open="true"]) #sidebar-box
{
  width: var(--nwdt) !important;
  border-right: var(--bdrr) !important;;
  border-image: var(--bdri) !important;;
  border-image-outset: var(--bdio) !important;;
  border-image-slice: var(--bdis) !important;;
  padding-left: calc(var(--spacing) / 2) !important;;
}

/* then add <from here> */
#main-window:not([titlepreface*="|| "]):has(#sidebar-box:hover) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:hover) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(#navigator-toolbox:focus-within) #navigator-toolbox,
#main-window:not([titlepreface*="|| "]):has(toolbarbutton[open="true"]) #navigator-toolbox
{
  animation-name: oflow;
  animation-duration: .01s;
  animation-delay: calc(var(--trans) / 2);
  animation-fill-mode: forwards;
}

@keyframes oflow {
  from {overflow: clip}
  to {overflow: visible}
}
/* <to here> */

/* line 452 */#main-window:not([titlepreface*="|| "]) #appcontent {
```
